module.exports = {
  up: (queryInterface) => queryInterface.bulkInsert(
    'Users',
    [
      {
        id: '98ef660e-c163-4e2e-8541-736cea7ecace',
        fullName: 'Jane Doe',
        email: 'janedoe@mail.com',
        password: '$2y$10$OkD2Z4xtHMuZEIhyKWeKo.Dz18bcTt9ZO8r6C9C4pV85kLvoX.AHu',
        verified: false,
        verificationToken: '',
        role: 'basic',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '9a23ab22-ce06-49ab-95b9-b66a259d5751',
        fullName: 'Jon Doe',
        email: 'jondoe@mail.com',
        password: '$2y$10$17n/ROhXf8H.Ls2cm5lLjeCQM4E7aWhc1at9GQT4Lha8sEbzsbFRm',
        verified: true,
        verificationToken: null,
        role: 'admin',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '210a4f65-2f82-4441-aa2d-e7312017fbac',
        fullName: 'Donald Doe',
        email: 'dondoe@mail.com',
        password: '$2y$10$l3OH.v9RYUDY42hvyTGJzu.UfBHoZV6sZN4jT8i5FWSWco.Q0JnNy',
        verified: true,
        verificationToken: null,
        role: 'superAdmin',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '5838540e-377f-4622-87f2-b40b62d380af',
        fullName: 'Hillary Doe',
        email: 'hilldoe@mail.com',
        password: '$2y$10$sUAnHMa/0DMH6fr6s1rxLOMeW/7CVQOV8xGXdUnzJqMUhvzJ81D/2',
        verified: false,
        verificationToken: '',
        role: 'basic',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '947eb4c8-626a-4b88-a6c9-070167e057bd',
        fullName: 'Jane Doharty',
        email: 'janedoh@mail.com',
        password: '$2y$10$EIG894mZ7yjfjJ4g6Tcl/.rVRdeP6gVHDmCuXOUpQD33Pqj6ziBvG',
        verified: false,
        verificationToken: '',
        role: 'basic',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '366d5f14-38b2-46af-b143-936d3662b6d8',
        fullName: 'Julius Ceaser',
        email: 'j.ceaser@mail.com',
        password: '$2y$10$IQfuXj/qS0vSdHDPNPcfnuNgQZfqkOmfvdeid8GnWQRQKtWzggCXu',
        verified: false,
        verificationToken: '',
        role: 'basic',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '2a4edc1e-d661-4f54-b7b0-52d079fcb8d1',
        fullName: 'Buhari Babangida',
        email: 'buhba@mail.com',
        password: '$2y$10$C1DtvugJqZhxuJBvZNV8o..vQxeTcAVWguwwIiXP1RrkX6mOz1VXm',
        verified: false,
        verificationToken: '',
        role: 'basic',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '9f43a310-d8f1-4ec2-af09-14c220ef938f',
        fullName: 'Jenny Wilson',
        email: 'wilsonjay@mail.com',
        password: '$2y$10$IbEnSTK9zmrYen89ADRs.OJB8EDV99.8ZK8wroSXIWQsINAuavU5G',
        verified: false,
        verificationToken: '',
        role: 'basic',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '276e29e2-f88f-4665-a838-01735266600a',
        fullName: 'Maria Kingsley',
        email: 'k-mar@mail.com',
        password: '$2y$10$AAxN66rGaDGkpNTn8rixCe7hDlQQ84EsIDK6glqsh4FAEFxyzWqrq',
        verified: false,
        verificationToken: '',
        role: 'basic',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: '93557528-33d9-4966-aa08-17780f66f563',
        fullName: 'Jennifer May',
        email: 'jenny_may@mail.com',
        password: '$2y$10$Nbg00xBYtMTqeYN78gbEZOT/9d9/oOpPLjmz.LLPdRW0yahdgMgy.',
        verified: false,
        verificationToken: '',
        role: 'basic',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    {},
  ),

  down: (queryInterface) => queryInterface.bulkDelete('Users', null, {}),
};
